#Following glusterfs official installation method
- name: Install common packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items: 
    - software-properties-common
  become: yes
  tags:
    - deploy

- name: Add glusterfs apt repository
  apt_repository:
    repo: ppa:gluster/glusterfs-3.8
    state: present
  become: yes
  tags: 
    - deploy

- name: Install glusterfs-server
  apt:
    name: glusterfs-server
    # it will auto install two other packages, glusterfs-client glusterfs-commons
    state: present
    update_cache: yes
  become: yes
  tags: 
    - deploy
  notify: restart gluster